window.require||!window.document||window._nodularJS_||(window._nodularJS_=new function(){function l(a){return a?a.A||a.s||("SCRIPT"==a.tagName?a.id||"SCRIPT TAG":null)||a:"(anonymous script)"}function y(a){var c=0,b,f,d;if(0!==a.length)for(b=0,d=a.length;b<d;b++)f=a.charCodeAt(b),c=(c<<5)-c+f,c|=0;c=c.toString();b=v[c];b||(b=[],v[c]=b);f=0;for(d=b.length;f<d;f++)if(b[f]===a)return{key:c,index:f,file:a};return{key:c,index:-1,file:a}}function p(a){a=y(a);return a.key+"_"+a.index}function z(a){this.description=
a;this.g=!0}function w(a){var c=document.currentScript;if(!c)throw new z("Cancelling script");1<e.loglevel&&console.warn("! Deferring "+l(c)+" (requires "+(a?a.file:"all files")+")");2<e.loglevel&&console.log("Adding "+l(c)+" to pending scripts ("+m.length+")");a=!1;for(var b=0,f=m.length;b<f;b++){var d=m[b];2<e.loglevel&&console.log(d.b);if(d.b>c.b){m.splice(b,0,c);a=!0;break}}a||m.push(c);var h=window.onerror;window.onerror=function(b,a,c,d,f){window.onerror=h;return"Aborting and defering script"===
b||"Aborting and defering script"===f?!0:f&&f.g};throw"Aborting and defering script";}function k(a){var c=[],b=null,f=p(a),d=[];this.status=g.NONE;this.B=function(){return f};this.file=function(){return a};this.G=function(){return c};this.w=function(){return d};this.sourceCode=function(){return b};this.v=function(){if(0==c.length)return"";var b=c[c.length-1],a=e.a[p(b)];return a?a.file()+" \u25c0 "+a.v():l(b)};this.i=function(b){for(var a=0,d=c.length;a<d;a++)if(c[a]===b)return;c.push(b)};this.C=
function(a){for(var b=0,c=d.length;b<c;b++)if(d[b]===a)return;d.push(a)};this.J=function(a){b=a};this.c=function(a){this.status=a;this.m&&this.m()}}var e=this;Object.defineProperty(this,"version",{enumerable:!0,configurable:!1,writable:!1,value:"0.9 beta"});var v={},q=[],m=[],r=[],t=0,u=0,n=0,g={NONE:n++,DOWNLOADING:n++,DOWNLOADED:n++,DOWNLOADERROR:n++,PREPARING:n++,ABORTED:n++,SUCCESS:n++};statusStr={};statusStr[g.NONE]="None";statusStr[g.DOWNLOADING]="Downloading";statusStr[g.DOWNLOADED]="Downloaded";
statusStr[g.DOWNLOADERROR]="Download error";statusStr[g.PREPARING]="Preparing";statusStr[g.ABORTED]="Aborted";statusStr[g.SUCCESS]="Success";this.pathPrefix="";this.forceDownloads=!1;this.loglevel=0;this.ModuleStatus=g;this.downloadWithRandomDeferTime=!1;this.a={};this.cleanScript=function(){var a=document.currentScript;a.innerHTML=a.innerHTML.replace(/\n\n\x3c!-- ___ FOOTER __ --\x3e[\s\S]*$/,"").replace(/^[\s\S]*\x3c!-- ___ HEADER __ --\x3e\n\n/,"");delete a.u};var x=null;this.checkRunPendingCodeNeeded=
function(){a:{x&&(clearTimeout(x),x=null);if(q.length)for(;;){for(var a=null,c=q.length,b=0;b<c;b++){var f=q[b],d;b:{d=f.w();for(var h=0,k=d.length;h<k;h++)if(e.a[p(d[h])].status<g.SUCCESS){d=!1;break b}d=!0}if(d){q.splice(b,1);a=f;break}}if(a){1<e.loglevel&&console.log("! Rerunning module "+a.file());a.j();break a}break}if(m.length)for(;;){a=null;c=m.length;for(b=0;b<c;b++){f=m[b];b:{(d=f)||console.error("NO SCRIPT!!");if(d.H)for(h in d=[],h=void 0,e.a)d.push(e.a[h]);else d=d.h;if(d&&d.length)for(h=
0,k=d.length;h<k;h++)if(d[h].status<g.SUCCESS){d=!1;break b}d=!0}if(d){m.splice(b,1);a=f;break}}if(a){1<e.loglevel&&console.log("! Rerunning script "+l(a));c=a;c.parentNode.removeChild(c);b=document.createElement("SCRIPT");c.type&&(b.type=c.type);b.s=c.s;b.A=c.A;b.b=c.b;c.u?(b.innerHTML=c.innerHTML,b.o=c.o):(b.o=c.innerHTML,b.innerHTML="var __error__=false;try{\n\n\x3c!-- ___ HEADER __ --\x3e\n\n"+c.innerHTML+"\n\n\x3c!-- ___ FOOTER __ --\x3e\n\n}catch(e){__error__=true;throw e}finally{if (!__error__)window._nodularJS_.checkRunPendingCodeNeeded();window._nodularJS_.cleanScript();}");
b.u=!0;b.id=c.id;for(key in e.a)for(a=e.a[key].G(),f=a.length,d=0;d<f;d++)if(a[d]===c){a[d]=b;break}c=b;2<e.loglevel&&console.log("Adding "+l(c));document.body.appendChild(c);2<e.loglevel&&console.log("Added  "+l(c))}else break}}};var A=0;this.F=function(a,c){if(document.currentScript){var b=document.currentScript;"undefined"==typeof b.b&&(b.b=A++)}if(a&&a.length){var f;if(document.currentScript)f=document.currentScript;else if(f=r[r.length-1])b=f.lastIndexOf("/"),b=1>b?"":f.substring(0,b),b.length&&
(a=b+"/"+a);var b=a.split("/"),d=b.length;res=[];for(i=0<d&&"."==b[0]?1:0;i<d;){var h=b[i++];".."==h&&res.length&&".."!==res[res.length-1]?res.pop():res.push(h)}a=1==res.length||".."!=res[0]?"./"+res.join("/"):res.join("/");2<e.loglevel&&console.log(l(f)+" required "+a);b=p(l(f));(b=e.a[b])&&b.C(a);b=y(a);if(-1==b.index)if(2<e.loglevel&&console.log("Never heard of "+a+" (currently in "+l(f)+")"),v[b.key].push(b.file),d=new k(b.file),d.i(f),e.a[d.B()]=d,d.download(c),document.currentScript)document.currentScript.h=
document.currentScript.h||[],document.currentScript.h.push(d),w(b);else throw new z(b.file+" was required in an anonymous script");else{if((d=e.a[p(a)])&&d.status>=g.SUCCESS)return 2<e.loglevel&&console.log("Already run successfully: "+a),d.i(f),d.f;2<e.loglevel&&console.log("Still not run successfully: "+a);w(b)}}else 2<e.loglevel&&console.log(l(f)+" required ALL"),document.currentScript&&(document.currentScript.H=!0),t!=u&&(2<e.loglevel&&console.log(t+" requested, "+u+" ready, deferring..."),w(null)),
2<e.loglevel&&console.log(t+" requested, "+u+" ready, moving on...")};k.prototype.src=function(){return(""+window._nodularJS_.pathPrefix+this.file()).replace(/\/\.\//g,"/")};k.prototype.I=function(){(function(){var a=this.module={exports:{}};eval('var module = this["module"];\n\n'+this.sourceCode());this.f=this.module.exports;if(this.module!==a)throw"Error: module was replaced in required file ${this.file()}";1<e.loglevel&&("undefined"!==typeof this.module.f&&console.log("  -> "+this.file()+" exports: "+
typeof this.module.f),3<e.loglevel&&console.log("  -> exports: "+this.module.f))}).call(this)};k.prototype.D=function(){this.c(g.PREPARING);try{1<e.loglevel&&console.log(">>> Executing "+this.file()),this.I()}catch(a){throw a.g&&1<e.loglevel&&console.warn("<<< Aborted "+this.file()+" (requires "+this.w().slice(-1)[0]+")"),this.c(g.ABORTED),a;}finally{}this.c(g.SUCCESS)};k.prototype.j=function(){try{this.D()}catch(a){if(a.g)q.push(this);else throw a;}};k.prototype.m=function(){2<e.loglevel&&console.error("Modules: "+
JSON.stringify(e.a,null,"\t"));switch(this.status){case g.DOWNLOADING:t++;break;case g.PREPARING:r.push(this.file());break;case g.ABORTED:r.pop();break;case g.SUCCESS:r.pop(),u++,e.checkRunPendingCodeNeeded()}if(e.onmodulestatuschange)e.onmodulestatuschange(this)};k.prototype.download=function(a){this.c(g.DOWNLOADING);var c=new XMLHttpRequest;c.l=this;c.onreadystatechange=function(){if(4===c.readyState){var a=this.l;if(200===c.status)a.J(this.responseText),a.c(g.DOWNLOADED),1<e.loglevel&&console.log("Received "+
c.l.file()),a.j();else throw a.c(g.DOWNLOADERROR),new URIError(a.src()+" not accessible, status: "+c.status+", (required by "+a.v()+")");}};var b=this.src();if(e.forceDownloads||a)b=-1<b.indexOf("?")?b+("&"+Math.random()):b+("?"+Math.random());c.open("GET",b,!0);e.downloadWithRandomDeferTime?setTimeout(function(){c.send(null)},2E3*Math.random()):c.send(null)};k.prototype.toJSON=function(){return"{file: "+this.file()+", status: "+statusStr[this.status]+"}"}},window.require=window._nodularJS_.F);
